### ISSUE TITLE
Opening a file doesn't do anything

### ISSUE THREAD

**Issue by JekiTheMonkey** [Opticos/OpenInWSL-Source#18]
I have installed trial version of the OpenInWSL from Windows Store, however anytime I try to follow any usage example it doesn't do anything, except saying `.txt >> Arch`.

The distro that I have on my WSL is Arch, and I use nvim to open text files, so I tried to do using OpenInWSL. I had added a file association selecting Arch as the distro, and the command is the following: `nvim #fpth#`. If I try to `Test Configuration` it doesn't do anything either, except, as said before, saying `,txt >> Arch`.

The distro is pretty fresh, I have installed it today, I don't think that something may be wrong with it.

**Comment by JekiTheMonkey** [comment]
Apparently that's only the case with nvim. Zathura works fine for me, even though it takes like 5 seconds to open a file. I don't know whether it supposed to take that long or maybe I can speed up the process somehow.

**Comment by Pololot64** [comment]
I think the speed really depends on your pc. As for nvim not working, I am assuming because it is not graphical in the same way other apps are.

**Comment by JekiTheMonkey** [comment]
I have a decent computer, in fact I have Ryzen 7 7700X as the CPU, and the WSL, the distro, and the files I'm trying to open are all on m2, so it should be fine.

So is it impossible to open nvim using OpenInWSL? I thought it wouldn't matter the nature of the application.

**Comment by Pololot64** [comment]
Can you look in the log? Maybe there is the neovim startup error in there. Otherwise, I'll try to launch it myself later.

**Comment by JekiTheMonkey** [comment]
The trial is over, I can't open anything anymore 😞 I'd appreciate if you would try it yourself.

But actually though where would I find the OpenInWSL log anyways? If I can open it without the app I guess I can try to.

**Comment by Pololot64** [comment]
The logs are in appdata/roaming/openinwsl/something.log. I don't remember the exact name. I'll try it. Sorry the trial ran out.. I don't think I have a way of extending it unfortunately :/

**Comment by JekiTheMonkey** [comment]
That's the whole main.log throughout my use of the program. It doesn't really look like it's different from what it says when I open zathura instead of nvim.
```
2023-08-06 21:01:27,938 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:01:28,114 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:01:38,611 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:01:38,805 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:02:00,617 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:02:00,790 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:02:10,084 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:02:10,285 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:03:43,589 - OpenInWSL 1.7 MSIX - ERROR - Cannot Open extension error
Traceback (most recent call last):
  File "main.py", line 2272, in <module>
  File "main.py", line 515, in path_converter
IndexError: string index out of range
2023-08-06 21:04:52,203 - OpenInWSL 1.7 MSIX - ERROR - Cannot Open extension error
Traceback (most recent call last):
  File "main.py", line 2272, in <module>
  File "main.py", line 515, in path_converter
IndexError: string index out of range
2023-08-06 21:05:12,766 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:05:12,938 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:07:54,863 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:07:55,020 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:08:00,426 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:08:00,627 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:08:35,369 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:08:35,620 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:09:11,572 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:09:11,824 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:09:34,613 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim ~/.config /mnt/i/asd.txt
2023-08-06 21:09:34,857 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:12:45,227 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:12:45,404 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:14:29,428 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:14:29,605 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:15:41,520 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:15:41,683 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-06 21:15:45,591 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/asd.txt
2023-08-06 21:15:45,764 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-07 11:29:21,355 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: zathura /mnt/j/warranty.pdf
2023-08-07 11:29:21,656 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-07 11:29:38,629 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: zathura /mnt/j/warranty.pdf
2023-08-07 11:29:38,844 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-07 11:30:10,558 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/swap/config.h
2023-08-07 11:30:10,796 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-07 13:10:00,688 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: zathura /mnt/i/documents/books/c++/effectivestl.pdf
2023-08-07 13:10:00,861 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-07 13:10:06,251 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: zathura '/mnt/i/documents/books/jesse schell - the art of game design a book of lenses .pdf'
2023-08-07 13:10:06,423 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-07 13:10:36,832 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/i/documents/books/tofind.txt
2023-08-07 13:10:37,013 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-07 20:32:58,281 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: nvim /mnt/j/.toolkit.config
2023-08-07 20:32:58,677 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
2023-08-07 20:33:25,584 - OpenInWSL 1.7 MSIX - INFO - RUN TEST: zathura /mnt/j/warranty.pdf
2023-08-07 20:33:25,753 - OpenInWSL 1.7 MSIX - INFO - No GWSL installed. Install or get another xserver
```

**Comment by Pololot64** [comment]
Just wondering, are you using any xserver or just wslg?

**Comment by JekiTheMonkey** [comment]
I have no clue, I have installed WSL to test it, so I'm not really familiar with it. I think it will be using the default one the WSL comes with.
