### ISSUE TITLE
OpenInWSL not working with fish as default shell

### ISSUE THREAD

**Issue by HawkinsT** [Opticos/OpenInWSL-Source#5]
When I change my default shell to fish via chsh, OpenInWSL no longer works (I'm afraid I haven't tried with zsh), regardless of how my config.fish file is set up. Keeping bash as the default shell and launching fish from .bashrc for interactive shells is a workaround I'm using for now, but it would be nice if this wasn't needed.

**Comment by Pololot64** [comment]
Did you try GWSL Dashboard -- Distro Tools -- More Shells and Options: export display and audio for fish? If that doesn't work it could be due to color theming.

**Comment by Pololot64** [comment]
Never mind, I just realized that I was looking in the wrong repository. Which graphical backend are you using?

**Comment by HawkinsT** [comment]
I've tried using a blank fish config but no luck there. I'm using GWSL; I've also tried setting 'Fish: Display/Audio Export', however this didn't make a difference.

Here's the anonymized log file (sorry it wasn't provided with the initial report); I tried opening this project's main.py for total reproducibility:
```
2021-09-14 09:23:03,078 - OpenInWSL 1.5 store - INFO - RUN TEST: emacs '/mnt/c/OpenInWSL-Source-main/main.py'
2021-09-14 09:23:07,260 - OpenInWSL 1.5 store - ERROR - Exception occurred - cannot spawn process
Traceback (most recent call last):
  File "main.py", line 353, in get_ip
NameError: name 'ipaddress' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 494, in spawn_n_run
  File "main.py", line 357, in get_ip
IndexError: list index out of range
```

**Comment by Pololot64** [comment]
I'll look into it. I am at school and so I do not have any era's but I will put it on my list.

**Comment by HawkinsT** [comment]
Thanks. One issue seems to be that ipaddress is never imported; in fact line 353 of main.py is the only place it's even referenced. I'd try importing it and see if that fixes the issue although the only Windows machine I currently have access to is my work laptop and it's a pain getting admin on that.

**Comment by Pololot64** [comment]
No worries. Thanks for doing digging 🙂
